# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlankStopWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlankStopWatch
  pod 'Alamofire', '~> 4.4'
  pod 'YouTubePlayer'

  target 'PlankStopWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlankStopWatchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
